services:
  mock-data-loader:
    image: docker.io/edenhill/kcat:1.7.1@sha256:8f16a5fed099931ce1122420b7473efe467ff9841d53680b99db25dd1723d711
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while true; do
        kcat -b kafka:9092 -K: -t fhir.all -P -l /data/mock-data.ndjson;
        kcat -b kafka:9092 -K: -t fhir.all-2 -P -l /data/mock-data-2.ndjson;
        sleep 10;
      done"
    volumes:
      - ./mock-data.ndjson:/data/mock-data.ndjson:ro
      - ./mock-data-2.ndjson:/data/mock-data-2.ndjson:ro
    depends_on:
      - kafka

  kafka:
    image: docker.io/bitnami/kafka:3.7.0@sha256:c1e54c8bc46edfc23c25d53f6de1b1433e2e919870c679fa7a846a8af0b03427
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_RAFT_CLUSTER_ID: "fhir-gateway"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "31457280"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_LOG_CLEANUP_POLICY: compact
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - 127.0.0.1:9094:9094

  akhq:
    image: tchiotludo/akhq:0.25.0@sha256:942807a2291f25b22047f8f56287e93cf9a43bf76f67a0eeca7e1eecc911c54c
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 127.0.0.1:9000:8080
    depends_on:
      - kafka
