services:
  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.21.6@sha256:47149d82a5e24248f97831baf406e5bb02f954016798051dcf4a39f845c3a435
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      DOTNET_EnableDiagnostics: "0"
      Vfps__Address: "dns:///vfps:8081"
      UseSystemTextJsonFhirSerializer: "true"
      PseudonymizationService: "Vfps"
    volumes:
      - ${PWD}/deploy/anonymization.yaml:/etc/anonymization.yaml:ro
    depends_on:
      - vfps

  loinc-converter:
    image: ghcr.io/miracum/loinc-conversion:v1.14.7@sha256:976a38044f131d773b547c7cbf07f977f9319ba43a661c628720b3d39c11dca6
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"

  vfps-db:
    image: docker.io/library/postgres:16.2@sha256:0e564daae78c2eea56ba57c64711bb9c408a512ce73cf81f9c78623354dd6976
    restart: unless-stopped
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps

  vfps:
    image: ghcr.io/miracum/vfps:v1.3.3@sha256:63f37d0541dc9742538cd65292abe314f668ff71308c3a68c8cc15f1281cc903
    restart: unless-stopped
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      DOTNET_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=vfps-db:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      # kics-scan ignore-line
      PGPASSWORD: postgres
      Pseudonymization__Caching__Namespaces__IsEnabled: "true"
    depends_on:
      - vfps-db

  fhir-server:
    image: docker.io/hapiproject/hapi:v6.10.1@sha256:4eac1b3481180b028616d1fab7e657e368538063d75f7ed3be2032e34c657dd4
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    deploy:
      resources:
        limits:
          memory: 4096m
    read_only: true
    tmpfs:
      - /tmp
      - /app/target
    privileged: false

  fhir-db:
    image: docker.io/library/postgres:16.2@sha256:0e564daae78c2eea56ba57c64711bb9c408a512ce73cf81f9c78623354dd6976
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  vfps-init-patient:
    image: docker.io/curlimages/curl:8.6.0@sha256:c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefused
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "PATIENT", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "p-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started

  vfps-init-fall:
    image: docker.io/curlimages/curl:8.6.0@sha256:c3b8bee303c6c6beed656cfc921218c529d65aa61114eb9e27c62047a1271b9b
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefused
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "FALL", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "f-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started
