services:
  jaeger:
    image: jaegertracing/all-in-one:1.41@sha256:a4f4e57343203e58c53874cb0c764b7523b8c3e2a308ebac845ed1b822166351

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.15.1@sha256:84d60b439bd1535de941a70c578b8e092f2d7091b57b887d55394588c72873de
    environment:
      Tracing__IsEnabled: "true"
      Tracing__Jaeger__AgentHost: jaeger
      Tracing__Jaeger__AgentPort: 6831
      Vfps__Address: "dns:///vfps:8081"
      UseSystemTextJsonFhirSerializer: "true"
      PseudonymizationService: "Vfps"
    volumes:
      - ${PWD}/deploy/anonymization.yaml:/etc/anonymization.yaml:ro
    depends_on:
      - jaeger
      - vfps

  loinc-converter:
    image: harbor.miracum.org/miracum-etl/loinc-conversion:v1.13.4@sha256:3522a3e463239c80a0d4ac7751fe188b160681a7e5dbeea3d998499eb7570125
    environment:
      JAEGER_AGENT_HOST: jaeger
    depends_on:
      - jaeger

  vfps-db:
    image: docker.io/library/postgres:15.1@sha256:f4cd32e7a418d9c9ba043e7d561243388202b654c740bcc85ca40b41d9fb4f1e
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
        reservations:
          memory: 1g
          cpus: "1"
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps

  vfps:
    image: ghcr.io/miracum/vfps:v1.1.3@sha256:a4940766829e5d5f330030e8813049d2f074651876853f672f45de0709e35fbf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "2"
        reservations:
          memory: 512m
          cpus: "2"
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      COMPlus_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=vfps-db:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      PGPASSWORD: postgres
      Tracing__IsEnabled: "true"
      Tracing__Jaeger__AgentHost: "jaeger"
      Pseudonymization__Caching__Namespaces__IsEnabled: "true"
    depends_on:
      - vfps-db

  fhir-server:
    image: docker.io/hapiproject/hapi:v6.2.2@sha256:9c4e8af94d81ac0049dbb589e4cd855bf78c9c13be6f6844e814c63d63545b44

  fhir-db:
    image: docker.io/library/postgres:15.1@sha256:f4cd32e7a418d9c9ba043e7d561243388202b654c740bcc85ca40b41d9fb4f1e
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  vfps-init-patient:
    image: docker.io/curlimages/curl:7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "PATIENT", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "p-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started

  vfps-init-fall:
    image: docker.io/curlimages/curl:7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "FALL", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "f-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started
