version: "3.7"

services:
  mock-data-loader:
    image: confluentinc/cp-kafkacat:7.1.3
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "while true; do
        kafkacat -b kafka1:19092 -K: -t fhir.all -P -l /data/mock-data.ndjson;
        kafkacat -b kafka1:19092 -K: -t fhir.all-2 -P -l /data/mock-data-2.ndjson;
        sleep 10;
      done"
    volumes:
      - ./mock-data.ndjson:/data/mock-data.ndjson:ro
      - ./mock-data-2.ndjson:/data/mock-data-2.ndjson:ro
    depends_on:
      - kafka1

  kafka1:
    image: docker.vectorized.io/vectorized/redpanda:v22.2.1
    container_name: kafka1
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka1:19092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092
      - 19092:19092
      - 9644:9644

  akhq:
    image: tchiotludo/akhq:0.22.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 9000:8080
    depends_on:
      - kafka1
