services:
  mock-data-loader:
    image: docker.io/edenhill/kcat:1.7.1@sha256:8f16a5fed099931ce1122420b7473efe467ff9841d53680b99db25dd1723d711
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while true; do
        kcat -b kafka1:19092 -K: -t fhir.all -P -l /data/mock-data.ndjson;
        kcat -b kafka1:19092 -K: -t fhir.all-2 -P -l /data/mock-data-2.ndjson;
        sleep 10;
      done"
    volumes:
      - ./mock-data.ndjson:/data/mock-data.ndjson:ro
      - ./mock-data-2.ndjson:/data/mock-data-2.ndjson:ro
    depends_on:
      - kafka1

  kafka1:
    image: docker.io/vectorized/redpanda:v23.1.12@sha256:fec54955f772e48fcc3f14b7cc2921465f5d0c92c4a198c57f42b2a76c60a377
    container_name: kafka1
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka1:19092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092
      - 19092:19092
      - 9644:9644

  akhq:
    image: tchiotludo/akhq:0.24.0@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 9000:8080
    depends_on:
      - kafka1
