services:
  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.21.4@sha256:d6ca458b427c5a5c3b2fcc0f8e1876855a811b604dec088faa190bc03089c5a7
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      DOTNET_EnableDiagnostics: "0"
      Vfps__Address: "dns:///vfps:8081"
      UseSystemTextJsonFhirSerializer: "true"
      PseudonymizationService: "Vfps"
    volumes:
      - ${PWD}/deploy/anonymization.yaml:/etc/anonymization.yaml:ro
    depends_on:
      - vfps

  loinc-converter:
    image: ghcr.io/miracum/loinc-conversion:v1.14.5@sha256:5b4e8eb90b32b46cf93a5fa7e26c239793b6f18a548d0021d80fc4a584d22901
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"

  vfps-db:
    image: docker.io/library/postgres:16.1@sha256:bb4e68544120c654e8b4f7ffd731be76b8d30ed7ac3a53f454290f02cf253b7c
    restart: unless-stopped
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps

  vfps:
    image: ghcr.io/miracum/vfps:v1.3.2@sha256:3f53189024ab609b3b25f08b8270f9880a2d710d68e46d2d7a5e6258085de3d4
    restart: unless-stopped
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    environment:
      DOTNET_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=vfps-db:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      # kics-scan ignore-line
      PGPASSWORD: postgres
      Pseudonymization__Caching__Namespaces__IsEnabled: "true"
    depends_on:
      - vfps-db

  fhir-server:
    image: docker.io/hapiproject/hapi:v6.10.1@sha256:4eac1b3481180b028616d1fab7e657e368538063d75f7ed3be2032e34c657dd4
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    deploy:
      resources:
        limits:
          memory: 4096m
    read_only: true
    tmpfs:
      - /tmp
      - /app/target
    privileged: false

  fhir-db:
    image: docker.io/library/postgres:16.1@sha256:bb4e68544120c654e8b4f7ffd731be76b8d30ed7ac3a53f454290f02cf253b7c
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  vfps-init-patient:
    image: docker.io/curlimages/curl:8.5.0@sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "PATIENT", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "p-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started

  vfps-init-fall:
    image: docker.io/curlimages/curl:8.5.0@sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    command: |
      -X POST
      -H 'Content-Type: application/json'
      --fail
      --retry-connrefuse
      --connect-timeout 10
      --max-time 120
      --retry 10
      --retry-delay 10
      -d '{"name": "FALL", "pseudonymGenerationMethod": 0, "pseudonymLength": 32, "pseudonymPrefix": "f-"}'
      http://vfps:8080/v1/namespaces
    depends_on:
      vfps:
        condition: service_started
