name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@99097e53ffa6d6e73b7f0a25fc33125cfc7a5102 # v1.5.0
    permissions:
      contents: read
      issues: write
      security-events: write
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
